import type { NewsItem } from "./newsTypes";

export const mockNews: NewsItem[] = [
  {
    id: "news-1",
    title: "AI 伺服器需求升溫，台積電先進製程接單續強",
    summary: "市場預期 AI 伺服器與高效能運算需求延續，帶動 3 奈米與 CoWoS 產能利用率維持高檔。",
    source: "示範資料",
    publishedAt: "2026-06-02 08:30",
    url: "https://example.com/news/tsmc-ai-demand",
    category: "半導體",
    relatedSymbols: ["2330"],
    relatedStockNames: ["台積電"],
    tags: ["熱門", "台股", "半導體"],
  },
  {
    id: "news-2",
    title: "聯發科傳新一代旗艦晶片提前驗證，供應鏈關注下半年動能",
    summary: "法人指出，旗艦平台若提前進入驗證，有望推升下半年 Android 陣營高階手機規格升級速度。",
    source: "示範資料",
    publishedAt: "2026-06-02 09:10",
    url: "https://example.com/news/mediatek-chip-validation",
    category: "半導體",
    relatedSymbols: ["2454"],
    relatedStockNames: ["聯發科"],
    tags: ["台股", "半導體"],
  },
  {
    id: "news-3",
    title: "金融股除權息行情暖身，市場關注殖利率與資本結構",
    summary: "隨著股東會與除權息旺季接近，金融股資本適足率與現金股利政策成為市場焦點。",
    source: "示範資料",
    publishedAt: "2026-06-02 10:20",
    url: "https://example.com/news/financial-dividend-season",
    category: "金融",
    relatedSymbols: [],
    relatedStockNames: [],
    tags: ["熱門", "金融"],
  },
  {
    id: "news-4",
    title: "美股科技股財報前觀望升溫，費半指數高檔震盪",
    summary: "投資人等待大型科技股新一輪財報，半導體設備與雲端資本支出預測成為盤面關鍵。",
    source: "示範資料",
    publishedAt: "2026-06-02 11:05",
    url: "https://example.com/news/us-tech-earnings-watch",
    category: "美股",
    relatedSymbols: [],
    relatedStockNames: [],
    tags: ["熱門", "美股", "半導體"],
  },
  {
    id: "news-5",
    title: "航運報價變動牽動長榮股價，法人聚焦旺季運價續航力",
    summary: "紅海與歐洲線運價波動仍大，市場評估旺季前後航商報價策略與現金流穩定性。",
    source: "示範資料",
    publishedAt: "2026-06-02 13:40",
    url: "https://example.com/news/evergreen-shipping-rates",
    category: "台股",
    relatedSymbols: ["2603"],
    relatedStockNames: ["長榮"],
    tags: ["台股", "熱門"],
  },
  {
    id: "news-6",
    title: "ETF 資金續流入，0050 再成市場焦點",
    summary: "大型權值 ETF 持續獲資金青睞，投資人關注台灣 50 權值股輪動與長線配置價值。",
    source: "示範資料",
    publishedAt: "2026-06-02 14:25",
    url: "https://example.com/news/etf-0050-focus",
    category: "台股",
    relatedSymbols: ["0050"],
    relatedStockNames: ["元大台灣50"],
    tags: ["台股", "熱門"],
  },
];
